name: "test"
dirs:
  - "${HOME}/Documents"
rules:
  - name: "movie"
    move_to: "${HOME}/Videos"
    rm_dir_if_empty: true #如果所在目录为空，则删除该目录
    rm_ignore: # 删除目录判空时，忽略名称包含以下字符的文件或文件夹
      - ".torrent"
    recursion: false
    extensions:  # 后缀名匹配
      - ".mp4"
      - ".mkv"
    regulars: # 正则匹配
      - 'org'
    rename: # 重命名规则（正则）
      - ori: "电影天堂"
        new: ""
      - ori: "阳光电影"
        new: ""
    overwrite: false # 覆盖同名文件，false则递增文件名
